id: P005464
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 11:51:56.867652
source_metadata:
  id: bdr:W29013
  title: པཎ་ཆེན་སྐུ་ཕྲེང་རིམ་བྱོན་གྱི་མཛད་རྣམ
  author: ''
  volumes:
    b463fe3241a94524a8c355f7558ae911:
      image_group_id: I5016
      title: ''
      volume_number: 1
      total_pages: 946
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
